from highcharts.views.bar import HighChartsBarView
from highcharts.views.line import HighChartsLineView
from highcharts.views.area import HighChartsAreaView
from highcharts.views.multiple_axes import HighChartsMultiAxesView
from highcharts.views.pie import HighChartsPieView
from highcharts.views.speedometer import HighChartsSpeedometerView
from highcharts.views.multiple_axes import HighChartsStockView
from highcharts.views.heatmap import HighChartsHeatMapView
from highcharts.views.polar import HighChartsPolarView
from highcharts.views.multiple_axes import HighChartsMultiXAxesView